apiVersion: v1
kind: ConfigMap
metadata:
  name: geo-app-config
  namespace: default
data:
    SERVER_PORT: "1441"
    SPRING_APPLICATION_NAME: "geodistance"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"