spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: 192.168.80.129
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://192.168.80.129:7080/realms/demo-realm"
          jwk-set-uri: "http://192.168.80.129:7080/realms/demo-realm/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      easybank:
        gatewayserver: DEBUG
    # Add these lines for detailed security logging
#    org.springframework.security: DEBUG
#    org.springframework.web.server: DEBUG
#    reactor.netty: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
