version: "3.8"
services:
  redis1:
    image: redis:latest
    container_name: cluster_redis1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      redis_net1:
        ipv4_address: 172.28.10.10
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
      - redis1_data_master:/data
    restart: unless-stopped



#docker user-defined networks are isolated — containers on different networks can't
#reach each other by service name or their internal IPs, so the replica must be on a network that can reach the master.
# Replication needs the replica to open a TCP connection to the master. Putting both containers on the same network makes the master reachable by IP or service name and enables Docker DNS resolution.
# Alternatives (how you can make the replica reach the master)
# Attach the replica to the master’s network (temporary, without changing compose):
# docker network connect redis_net1 cluster_redis2
# This adds cluster_redis2 to redis_net1 so it can reach redis1 internally

  redis2:
    image: redis:latest
    container_name: cluster_redis2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
    networks:
      redis_net1:
        ipv4_address: 172.28.10.11
    volumes:
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
      - redis2_data_slave:/data
    restart: unless-stopped


networks:
  redis_net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24
          gateway: 172.28.10.1

volumes:
  redis1_data_master:
  redis2_data_slave:

