daemonize no
bind 0.0.0.0
port 6379
protected-mode no

requirepass 123456

# This instance is a replica of redis1 (master)
replicaof 192.168.80.129 6379

# Password to authenticate with master
masterauth 123456

# Ensure replica is read-only for client commands
replica-read-only yes
# backward-compatible directive name
slave-read-only yes

# Data directory
dir /data



save 900 1
save 300 10
save 60 10000

dbfilename dump.rdb




appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
# 这个“64mb”是文件大小（磁盘/文件系统上的字节数），不是内存或 CPU 的数值
auto-aof-rewrite-min-size 64mb