version: "3.8"
services:
  redis1:
    image: redis:latest
    container_name: cluster_redis1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      redis_net1:
        ipv4_address: 172.28.10.10
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis1_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis2:
    image: redis:latest
    container_name: cluster_redis2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
    networks:
      redis_net2:
        ipv4_address: 172.28.20.10
    volumes:
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis2_data:/data
    restart: unless-stopped

  redis3:
    image: redis:latest
    container_name: cluster_redis3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6381:6379"
    networks:
      redis_net3:
        ipv4_address: 172.28.30.10
    volumes:
      - ./redis3/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis3_data:/data
    restart: unless-stopped

  redis4:
    image: redis:latest
    container_name: cluster_redis4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6382:6379"
    networks:
      redis_net4:
        ipv4_address: 172.28.40.10
    volumes:
      - ./redis4/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis4_data:/data
    restart: unless-stopped

networks:
  redis_net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24
          gateway: 172.28.10.1
  redis_net2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.20.0/24
          gateway: 172.28.20.1
  redis_net3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.30.0/24
          gateway: 172.28.30.1
  redis_net4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.40.0/24
          gateway: 172.28.40.1

volumes:
  redis1_data:
  redis2_data:
  redis3_data:
  redis4_data:
