bind 0.0.0.0
port 6379
protected-mode no
requirepass 123456

# This instance is a replica of redis1 (master)
replicaof 172.28.10.10 6379

# Password to authenticate with master
masterauth 123456

# Ensure replica is read-only for client commands
replica-read-only yes
# backward-compatible directive name
slave-read-only yes

# Data directory
dir /data
